# Generated by Django 3.1.6 on 2021-02-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20210208_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(default='middle_name', max_length=30),
            preserve_default=False,
        ),
    ]
